version: silfur-rev{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - develop
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: x64
clone_depth: 5
init:
- cmd: >-
    appveyor DownloadFile https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe?Human=true -FileName VulkanSDK.exe

    .\VulkanSDK.exe /S

    rm -f VulkanSDK.exe
environment:
  VULKAN_SDK: C:\VulkanSDK\1.2.131.2
install:
- cmd: >-
    git submodule update --init --recursive

    cd scripts

    echo | call Win-GenProjects.bat

    echo | call CompileShaders.bat

    cd ..
build:
  parallel: true
  verbosity: minimal