version: silfur-rev{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - develop
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: x64
clone_depth: 5
init:
- cmd: >-
    appveyor DownloadFile https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe?Human=true -FileName VulkanSDK.exe

    .\VulkanSDK.exe /S

    rm -f VulkanSDK.exe
environment:
  VULKAN_SDK: C:\VulkanSDK\1.2.131.2
install:
- cmd: >-
    git submodule update --init --recursive

    cd scripts

    echo | call Win-GenProjects.bat

    echo | call CompileShaders.bat

    cd ..
build:
  parallel: true
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/693970624837844992/ySJF5HYgvWZBjvRFKgNvtJMHNSeFEeBEnCj840virdrjmPT8NiTtSsokakyzeH7XCnWF
  method: POST
  content_type: application/json
  body: >-
    {
      "embeds": [
        {
          "title": "Build {{buildId}}",
          "url": "{{buildUrl}}",
          "color": {{#passed}}40973{{/passed}}{{^passed}}11672839{{/passed}},
          "footer": {
            "icon_url": "{{#passed}}https://i.imgur.com/Rf4g8v6.png{{/passed}}{{^passed}}https://i.imgur.com/QaERwAW.png{{/passed}}",
            "text": "{{#passed}}Success{{/passed}}{{^passed}}Failure{{/passed}}"
          },
          "author": {
            "name": "{{commitAuthor}}",
            "url": "https://github.com/{{repositoryName}}/commit/{{commitId}}"
          },
          "fields": [
            {
              "name": "Commit",
              "value": "[{{commitMessage}}](https://github.com/{{repositoryName}}/commit/{{commitId}})"
            },
            {
              "name": "Duration",
              "value": "{{duration}}",
              "inline": true
            },
            {
              "name": "Build version",
              "value": "{{buildVersion}}",
              "inline": true
            }
          ]
        }
      ]
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false